baseURL = "https://azharmgh.github.io/"
languageCode = "en-us"
title = "Azhar Manzoor"
theme = "PaperMod"


sectionPagesMenu = "main"


[params.profileMode]
enabled = true
title =  "Azhar Manzoor"
subtitle = "Software and Solution Archtiect"
imageUrl = "azhar.png"
imageTitle = "Azhar Manzoor" 
imageWidth = 120  
imageHeight = 120    
[[buttons]]
name = "Github"
url = "https://github.com/"

[[socialIcons]]
name = "LinkedIn"
url = "https://linkedin.com"

[[socialIcons]]
name = "github"
url = "https://github.com/"

        
        
